config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :gestiones
   root 'gestiones#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gestione.rb
class Gestione < ApplicationRecord
 belongs_to :user
 mount_uploader :my_file, FileUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    has_many :gestiones
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/gestiones_controller.rb
class GestionesController < ApplicationController
  before_action :set_gestione, only: [:show, :edit, :update, :destroy]

  # GET /gestiones
  # GET /gestiones.json
  def index
    
    if current_user
  @gestiones = current_user.gestiones
  else
  @gestiones = Gestione.all
   end
  end

  # GET /gestiones/1
  # GET /gestiones/1.json
  def show
  end

  # GET /gestiones/new
  def new
    @gestione = Gestione.new
  end

  # GET /gestiones/1/edit
  def edit
  end

  # POST /gestiones
  # POST /gestiones.json
  def create
    @gestione = Gestione.new(gestione_params)
    @gestione.user_id = current_user.id
    @gestione.my_file = params[:file]
    respond_to do |format|
      if @gestione.save
        format.html { redirect_to @gestione, notice: 'Gestione was successfully created.' }
        format.json { render :show, status: :created, location: @gestione }
      else
        format.html { render :new }
        format.json { render json: @gestione.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gestiones/1
  # PATCH/PUT /gestiones/1.json
  def update
    respond_to do |format|
      if @gestione.update(gestione_params)
        format.html { redirect_to @gestione, notice: 'Gestione was successfully updated.' }
        format.json { render :show, status: :ok, location: @gestione }
      else
        format.html { render :edit }
        format.json { render json: @gestione.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gestiones/1
  # DELETE /gestiones/1.json
  def destroy
    @gestione.destroy
    respond_to do |format|
      format.html { redirect_to gestiones_url, notice: 'Gestione was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gestione
      @gestione = Gestione.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gestione_params
      params.require(:gestione).permit(:user_id, :nombre, :correo, :telefono, :departamento, :descripcion, :my_file)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gestiones_helper.rb
module GestionesHelper
end

app/views/gestiones/_form.html.erb
<%= form_for(gestione) do |f| %>
  <% if gestione.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gestione.errors.count, "error") %> prohibited this gestione from being saved:</h2>

      <ul>
      <% gestione.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :nombre %>
    <%= f.text_field :nombre %>
  </div>

  <div class="field">
    <%= f.label :correo %>
    <%= f.text_field :correo %>
  </div>

  <div class="field">
    <%= f.label :telefono %>
    <%= f.text_field :telefono %>
  </div>

  <div class="field">
    <%= f.label :departamento %>
    <%= f.text_field :departamento %>
  </div>

  <div class="field">
    <%= f.label :descripcion %>
    <%= f.text_area :descripcion %>
  </div>

  <div class="file-field input-field">
    <div class="btn">
      <span>Archivo</span>
        <%= f.file_field :my_file %>
    </div>
    <div class="file-path-wrapper">
      <input class="file-path validate" type="text">
    </div>
    </div>

<div class="actions">
    <%= f.submit "Guardar",class: 'waves-effect waves-ligt btn' %>
  </div>
<% end %>

app/views/gestiones/edit.html.erb
<h1>Edicion de Gestion</h1>

<%= render 'form', gestione: @gestione %>



<div class="row">
  <div class="col s12">
    <%= link_to 'Atras', gestiones_path, class: 'waves-effect waves-light btn', style: 'color: white' %>
  </div>
</div>

app/views/gestiones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gestion de Documentos ED2 </h1>

<table class="highlight">
  <thead>
    <tr>
      <th>IDUser</th>
      <th>Nombre</th>
      <th>Correo</th>
      <th>Telefono</th>
      <th>Departamento</th>
      <th>Descripcion</th>
      <th>Adjunto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gestiones.each do |gestione| %>
     
      <tr>

        <td><%= gestione.user_id %></td>
        <td><%= gestione.nombre %></td>
        <td><%= gestione.correo %></td>
        <td><%= gestione.telefono %></td>
        <td><%= gestione.departamento %></td>
        <td><%= gestione.descripcion %></td>
        <td><a href="<%= gestione.my_file %>">Descargar</a></td>
        <td><a href=http://localhost:3000/rails/mailers/example_mailer/sample_mail_preview.html <a class="waves-effect waves-light btn">Correo ></a></td>
        <td><a href= "/gestiones/<%= gestione.id%>"<a class="waves-effect waves-light btn">Mostrar</a></td>
        <td><a href= "/gestiones/<%= gestione.id%>/edit" class="waves-effect waves-light btn">Editar</a></td>
        <td>
  <a data-method="delete" href =/gestiones/<%= gestione.id %> data-confirm="Seguro?" class="waves-effect waves-light btn">Eliminar</a>  
  </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<a href="/gestiones/new"class="waves-effect waves-light btn">Nueva Gestion</a>

app/views/gestiones/new.html.erb
<h1>Formulario de Registro</h1>

<%= render 'form', gestione: @gestione %>


<div class="row">
  <div class="col s12">
    <%= link_to 'Atras', gestiones_path, class: 'waves-effect waves-light btn', style: 'color: white' %>
  </div>
</div>

app/views/gestiones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>ID:</strong>
  <%= @gestione.user_id %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @gestione.nombre %>
</p>

<p>
  <strong>Correo:</strong>
  <%= @gestione.correo %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @gestione.telefono %>
</p>

<p>
  <strong>Departamento:</strong>
  <%= @gestione.departamento %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @gestione.descripcion %>
</p>

<p>
  <strong>My file:</strong>
  <%= @gestione.my_file %>
</p>


<div class="row">
  <div class="col s12">
    <%= link_to 'Editar',  edit_gestione_path(@gestione), class: 'waves-effect waves-light btn', style: 'color: white' %>
  </div>
</div>

<div class="row">
  <div class="col s12">
    <%= link_to 'Atras', gestiones_path, class: 'waves-effect waves-light btn', style: 'color: white' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sistema de Gestion</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

<!--Import Google Icon Font-->
  <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <!--Import materialize.css-->
  <link type="text/css" rel="stylesheet" href="/css/materialize.min.css"  media="screen,projection"/>

  <!--Let browser know website is optimized for mobile-->
  </head>

  

  <body>
    
<div class ="container">
 <% if !current_user %>
   <%= link_to "Iniciar Sesion", "/users/sign_in" %>
   <% else %>
   Bienvenido <%= current_user.email %>
   <%= link_to destroy_user_session_path, :method => :delete  do %>Cerrar Sesion<%end%>
   <%end%>
   <%= yield %>
      <!--Import jQuery before materialize.js-->
      <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
      <script type="text/javascript" src="js/materialize.min.js"></script>
   </div>

  
    

    
  </body>
</html>